@echo off

start chrome --user-data-dir="C:\Users\Michael Sorensen\AppData\Local\Google\Chrome\User Data\Default"--new-window --window-position=0,0 --window-size=820,700 "http://localhost:5000"
start chrome --user-data-dir="C:\Users\Michael Sorensen\AppData\Local\Google\Chrome\User Data\user2" --new-window --window-position=820,0 --window-size=820,700 "http://localhost:5000"
start chrome --user-data-dir="C:\Users\Michael Sorensen\AppData\Local\Google\Chrome\User Data\user3"--new-window --window-position=0,600 --window-size=820,700 "http://localhost:5000"
start chrome --user-data-dir="C:\Users\Michael Sorensen\AppData\Local\Google\Chrome\User Data\user4"--new-window --window-position=820,600 --window-size=820,700 "http://localhost:5000"
start chrome --user-data-dir="C:\Users\Michael Sorensen\AppData\Local\Google\Chrome\User Data\user5"--new-window --window-position=0,0 --window-size=820,700 "http://localhost:5000"
start chrome --user-data-dir="C:\Users\Michael Sorensen\AppData\Local\Google\Chrome\User Data\user6" --new-window --window-position=820,0 --window-size=820,700 "http://localhost:5000"
start chrome --user-data-dir="C:\Users\Michael Sorensen\AppData\Local\Google\Chrome\User Data\user7"--new-window --window-position=0,600 --window-size=820,700 "http://localhost:5000"
start chrome --user-data-dir="C:\Users\Michael Sorensen\AppData\Local\Google\Chrome\User Data\user8"--new-window --window-position=820,600 --window-size=820,700 "http://localhost:5000"
start chrome --user-data-dir="C:\Users\Michael Sorensen\AppData\Local\Google\Chrome\User Data\user9"--new-window --window-position=0,0 --window-size=820,700 "http://localhost:5000"
start chrome --user-data-dir="C:\Users\Michael Sorensen\AppData\Local\Google\Chrome\User Data\user10" --new-window --window-position=820,0 --window-size=820,700 "http://localhost:5000"
start chrome --user-data-dir="C:\Users\Michael Sorensen\AppData\Local\Google\Chrome\User Data\user11"--new-window --window-position=0,0 --window-size=820,700 "http://localhost:5000"
start chrome --user-data-dir="C:\Users\Michael Sorensen\AppData\Local\Google\Chrome\User Data\user12" --new-window --window-position=820,0 --window-size=820,700 "http://localhost:5000"
start chrome --user-data-dir="C:\Users\Michael Sorensen\AppData\Local\Google\Chrome\User Data\user13"--new-window --window-position=0,600 --window-size=820,700 "http://localhost:5000"
start chrome --user-data-dir="C:\Users\Michael Sorensen\AppData\Local\Google\Chrome\User Data\user14"--new-window --window-position=820,600 --window-size=820,700 "http://localhost:5000"
start chrome --user-data-dir="C:\Users\Michael Sorensen\AppData\Local\Google\Chrome\User Data\user15"--new-window --window-position=0,0 --window-size=820,700 "http://localhost:5000"
start chrome --user-data-dir="C:\Users\Michael Sorensen\AppData\Local\Google\Chrome\User Data\user16" --new-window --window-position=820,0 --window-size=820,700 "http://localhost:5000"
start chrome --user-data-dir="C:\Users\Michael Sorensen\AppData\Local\Google\Chrome\User Data\user17"--new-window --window-position=0,600 --window-size=820,700 "http://localhost:5000"
start chrome --user-data-dir="C:\Users\Michael Sorensen\AppData\Local\Google\Chrome\User Data\user18"--new-window --window-position=820,600 --window-size=820,700 "http://localhost:5000"
start chrome --user-data-dir="C:\Users\Michael Sorensen\AppData\Local\Google\Chrome\User Data\user19"--new-window --window-position=0,0 --window-size=820,700 "http://localhost:5000"
start chrome --user-data-dir="C:\Users\Michael Sorensen\AppData\Local\Google\Chrome\User Data\user20" --new-window --window-position=820,0 --window-size=820,700 "http://localhost:5000"
start chrome --user-data-dir="C:\Users\Michael Sorensen\AppData\Local\Google\Chrome\User Data\user21"--new-window --window-position=0,0 --window-size=820,700 "http://localhost:5000"
start chrome --user-data-dir="C:\Users\Michael Sorensen\AppData\Local\Google\Chrome\User Data\user22" --new-window --window-position=820,0 --window-size=820,700 "http://localhost:5000"
start chrome --user-data-dir="C:\Users\Michael Sorensen\AppData\Local\Google\Chrome\User Data\user23"--new-window --window-position=0,600 --window-size=820,700 "http://localhost:5000"
start chrome --user-data-dir="C:\Users\Michael Sorensen\AppData\Local\Google\Chrome\User Data\user24"--new-window --window-position=820,600 --window-size=820,700 "http://localhost:5000"
start chrome --user-data-dir="C:\Users\Michael Sorensen\AppData\Local\Google\Chrome\User Data\user25"--new-window --window-position=0,0 --window-size=820,700 "http://localhost:5000"

exit